let state = { communities: {}, revision: 0, selected: "" };
const $ = (id) => document.getElementById(id);
window.addEventListener("DOMContentLoaded", () => { $("login").addEventListener("click", login); $("logout").addEventListener("click", logout); $("add-community").addEventListener("click", addCommunity); $("save-community").addEventListener("click", saveCommunity); $("remove-community").addEventListener("click", removeCommunity); $("save-webhook").addEventListener("click", saveWebhook); checkSession(); });
async function api(url, options = {}) { const response = await fetch(url, { ...options, headers: { Accept: "application/json", ...(options.body ? { "Content-Type": "application/json" } : {}), ...(options.headers || {}) } }); let payload = {}; try { payload = await response.json(); } catch {} if (!response.ok) { const error = new Error(payload.message || "The request failed."); error.payload = payload; error.status = response.status; throw error; } return payload; }
async function checkSession() { try { await api("/api/admin/session"); showAdmin(); await load(); } catch {} }
async function login() { try { await api("/api/admin/login", { method: "POST", body: JSON.stringify({ password: $("password").value }) }); $("password").value = ""; showAdmin(); await load(); message("Signed in."); } catch (error) { showError(error); } }
async function logout() { await api("/api/admin/logout", { method: "POST" }).catch(() => {}); $("admin-panel").hidden = true; $("login-panel").hidden = false; $("logout").hidden = true; message("Signed out."); }
function showAdmin() { $("login-panel").hidden = true; $("admin-panel").hidden = false; $("logout").hidden = false; }
async function load() { state = { ...state, ...await api("/api/admin/config") }; const ids = Object.keys(state.communities); if (!state.selected || !state.communities[state.selected]) state.selected = ids[0] || ""; render(); clearConfigErrors(); }
function render() { $("community-list").innerHTML = Object.entries(state.communities).map(([id, c]) => `<button type="button" class="community-item ${id === state.selected ? "is-selected" : ""}" data-id="${escapeHtml(id)}">${escapeHtml(id)} <small>${c.active === false ? "Inactive" : "Active"}</small></button>`).join(""); document.querySelectorAll("[data-id]").forEach((button) => button.addEventListener("click", () => { state.selected = button.dataset.id; render(); })); const selected = state.communities[state.selected]; $("community-json").value = selected ? JSON.stringify(selected, null, 2) : ""; $("remove-community").disabled = !selected; $("webhook-status").textContent = state.webhookConfigured ? "A shared webhook is configured. Leave the field blank to clear it." : "No shared webhook is configured."; }
function addCommunity() { const id = $("new-community-id").value.trim(); if (!/^[A-Za-z0-9_-]{1,100}$/.test(id) || state.communities[id]) return message("Enter a unique valid community ID.", true); const base = state.communities[state.selected]; if (!base) return message("Load a community first.", true); state.communities[id] = structuredClone(base); state.communities[id].active = true; state.selected = id; $("new-community-id").value = ""; render(); }
async function saveCommunity() { let parsed; try { parsed = JSON.parse($("community-json").value); } catch { return message("Enter valid JSON.", true); } if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return message("The community configuration must be a JSON object.", true); if (!state.selected) return message("Select a community first.", true); if (!Object.prototype.hasOwnProperty.call(parsed, "active")) parsed.active = true; const communities = structuredClone(state.communities); communities[state.selected] = parsed; try { await persistCommunities(communities, state.selected, "Community saved."); } catch (error) { await handleSaveError(error); } }
async function removeCommunity() { if (!state.selected || Object.keys(state.communities).length < 2) return message("At least one community must remain.", true); const communities = structuredClone(state.communities); delete communities[state.selected]; const selected = Object.keys(communities)[0] || ""; try { await persistCommunities(communities, selected, "Community removed."); } catch (error) { await handleSaveError(error); } }
async function persistCommunities(communities, selected, successMessage) { const result = await api("/api/admin/config", { method: "PUT", body: JSON.stringify({ communities, revision: state.revision }) }); state.communities = communities; state.selected = selected; state.revision = result.revision; message(successMessage); render(); }
async function handleSaveError(error) { if (error.status === 409) { try { await load(); message("The server changed. Unsaved edits were discarded; review the current configuration and try again.", true); } catch (reloadError) { showError(reloadError); } return; } showError(error); }
async function saveWebhook() { try { const result = await api("/api/admin/discord", { method: "PUT", body: JSON.stringify({ webhook: $("webhook").value.trim(), revision: state.revision }) }); state.revision = result.revision; state.webhookConfigured = result.webhookConfigured; $("webhook").value = ""; message("Shared webhook saved."); render(); } catch (error) { await handleSaveError(error); } }
function message(text, error = false) { $("message").textContent = text; $("message").className = error ? "alert" : "notice"; if (!error) clearConfigErrors(); }
function showError(error) { const fields = error.payload?.fields; message(error.message.includes("JSON") ? "Enter valid JSON." : error.message, true); renderConfigErrors(Array.isArray(fields) ? fields : []); }
function renderConfigErrors(fields) { const region = $("config-errors"); region.replaceChildren(); if (!fields.length) { region.hidden = true; return; } const list = document.createElement("ul"); for (const field of fields) { const item = document.createElement("li"); item.textContent = field; list.append(item); } region.append(list); region.hidden = false; }
function clearConfigErrors() { const region = $("config-errors"); if (region) { region.replaceChildren(); region.hidden = true; } }
function escapeHtml(value) { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
