let state = { communities: {}, revision: 0, selected: "" };
const $ = (id) => document.getElementById(id);
window.addEventListener("DOMContentLoaded", () => { $("login").addEventListener("click", login); $("logout").addEventListener("click", logout); $("add-community").addEventListener("click", addCommunity); $("save-community").addEventListener("click", saveCommunity); $("remove-community").addEventListener("click", removeCommunity); $("save-webhook").addEventListener("click", saveWebhook); checkSession(); });
async function api(url, options = {}) { const response = await fetch(url, { ...options, headers: { Accept: "application/json", ...(options.body ? { "Content-Type": "application/json" } : {}), ...(options.headers || {}) } }); let payload = {}; try { payload = await response.json(); } catch {} if (!response.ok) { const error = new Error(payload.message || "The request failed."); error.payload = payload; throw error; } return payload; }
async function checkSession() { try { await api("/api/admin/session"); showAdmin(); await load(); } catch {} }
async function login() { try { await api("/api/admin/login", { method: "POST", body: JSON.stringify({ password: $("password").value }) }); $("password").value = ""; showAdmin(); await load(); message("Signed in."); } catch (error) { message(error.message, true); } }
async function logout() { await api("/api/admin/logout", { method: "POST" }).catch(() => {}); $("admin-panel").hidden = true; $("login-panel").hidden = false; $("logout").hidden = true; message("Signed out."); }
function showAdmin() { $("login-panel").hidden = true; $("admin-panel").hidden = false; $("logout").hidden = false; }
async function load() { state = { ...state, ...await api("/api/admin/config") }; const ids = Object.keys(state.communities); if (!state.selected || !state.communities[state.selected]) state.selected = ids[0] || ""; render(); }
function render() { $("community-list").innerHTML = Object.entries(state.communities).map(([id, c]) => `<button type="button" class="community-item ${id === state.selected ? "is-selected" : ""}" data-id="${escapeHtml(id)}">${escapeHtml(id)} <small>${c.active === false ? "Inactive" : "Active"}</small></button>`).join(""); document.querySelectorAll("[data-id]").forEach((button) => button.addEventListener("click", () => { state.selected = button.dataset.id; render(); })); const selected = state.communities[state.selected]; $("community-json").value = selected ? JSON.stringify(selected, null, 2) : ""; $("remove-community").disabled = !selected; $("webhook-status").textContent = state.webhookConfigured ? "A shared webhook is configured. Leave the field blank to clear it." : "No shared webhook is configured."; }
function addCommunity() { const id = $("new-community-id").value.trim(); if (!/^[A-Za-z0-9_-]{1,100}$/.test(id) || state.communities[id]) return message("Enter a unique valid community ID.", true); const base = state.communities[state.selected]; if (!base) return message("Load a community first.", true); state.communities[id] = structuredClone(base); state.communities[id].active = true; state.selected = id; $("new-community-id").value = ""; render(); }
async function saveCommunity() { try { const parsed = JSON.parse($("community-json").value); parsed.active = parsed.active !== false; state.communities[state.selected] = parsed; const result = await api("/api/admin/config", { method: "PUT", body: JSON.stringify({ communities: state.communities, revision: state.revision }) }); state.revision = result.revision; message("Community saved."); render(); } catch (error) { message(error.message.includes("JSON") ? "Enter valid JSON." : error.message, true); } }
async function removeCommunity() { if (!state.selected || Object.keys(state.communities).length < 2) return message("At least one community must remain.", true); delete state.communities[state.selected]; state.selected = Object.keys(state.communities)[0]; await saveCommunity(); }
async function saveWebhook() { try { const result = await api("/api/admin/discord", { method: "PUT", body: JSON.stringify({ webhook: $("webhook").value.trim(), revision: state.revision }) }); state.revision = result.revision; state.webhookConfigured = result.webhookConfigured; $("webhook").value = ""; message("Shared webhook saved."); render(); } catch (error) { message(error.message, true); } }
function message(text, error = false) { $("message").textContent = text; $("message").className = error ? "alert" : "notice"; }
function escapeHtml(value) { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
